---
title: "Notebook"
author: "Richard Layton"
date: "June 12, 2016"
output: html_document
subtitle: Workshop on creating reproducible reports
---

### 2016-06-16

Completed script to annotate the image of the load cell setup. Thi could be a lesson in the course and possibly a package. Would have to develop each of the functions.


### 2016-06-13

Before the tutorial, motivate the work by examining the polished report and identify elements that change when the data change.

The tutorial is a web page

- Open the default Rmd file, compile it, and examine its features 
- Change the YAML, delete text, start your own report 
- import an image 
- do a little bit of R in the Rmd file, compile 
- move to an R script to do more analysis (in the same order as it is expected in the report) 
- then source it in the Rmd, two ways of getting R script into the RR 
- work in R and Rmd to add prose and do further analysis, bringing results into the report in logical flow 
- add simple formatting as we go too but leave more advanced formatting for later 
- repeat until report complete 
- then the advanced formatting 

How to thing about the flow of the tutorial 

- the linear flow is the same as the linear flow of the report 
- same organization as the final polished document  
- create a start-up folder for the participants to download containing t he 4 data sets and the one image---everything else they will create, though I should probably provide the scripts for the final polished report for reference

When I get to the "planning for reproducibility" section 

- show the general directory structure 
- illustrate it by showing an example using all the files we just used in the calibration example, and where each file would reside 
- then show where the code would change too 


_Some thoughts following the Bll Kline seminar today_ 

- email to Yosi, Eric Reyes, John McSweeney about DSR-RHIT repo. 
- ask if them if they want to join and who else they cam invite 
- consider starting a Rose useR group?  




### 2016-06-12

Applied the new directory structure to this R Project. 

TO-DO:

- re-compile each of the Rmd and Rnw files and correct the relative paths 
- same for the scripts that create the fictitious calibration data 
- it's OK to create two data tables, on in wide and one in long format 
- use the DiagrammeR package to draw directory trees? 

Or just do this: 

```
project\
    |-- data\
    |-- manage\
    |-- reports\
    |-- results\
    \-- scripts\
  
data\
    |-- 2015-02\
    |-- 2015-08\
    \-- 2016-01\
          |-- data.xlsx
          \-- other-data.csv
```





