---
title: Workshop agenda
date: 2016-08-24
output:
  tufte::tufte_handout: default
---

```{r setup, include=FALSE, echo=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

library(knitr)
opts_knit$set(root.dir="../")
opts_chunk$set(include=TRUE, echo=FALSE, message=FALSE)
```

```{r}
library(readxl)
library(dplyr)
df <- read_excel("assets/agenda.xlsx") %>% 
  select(time, activity, format)

sel1 <- df$activity == 'day 1'
sel2 <- df$activity == 'day 2'

idx1 <- which(df$activity %in% 'day 1')
idx2 <- which(df$activity %in% 'day 2')
n <- length(df$activity)

df1 <- df[(idx1 + 1):(idx2 - 1), ]
df2 <- df[(idx2 + 1):n, ]

df1[is.na(df1)] <- " " # replaces NAs with blanks
df2[is.na(df2)] <- " " # replaces NAs with blanks
```

## Session 1

To get the most out of the first session, do the pre-workshop homework before arriving. 

```{r}
kable(df1, format.args = list())
```

## Session 2

To get the most out of the second session, complete the sample report tutorial before the second session.  

```{r}
kable(df2)
```
