---
layout: page
title:  getting started
tagline: agenda 
output: html_document
---

<!-- because this Rmd file is executed from the runall script, I use relative paths from the pages directory, thus to read the data file, "../data/file" 
The file can still be run on its own.-->

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(include=TRUE, echo=FALSE, message=FALSE)

library(readxl)
library(dplyr)
df <- read_excel("../data/agenda.xlsx") %>% 
	mutate(space1 = NA, space2 = NA) %>%
  select(time, space1, activity, space2, format) %>%
	rename(' ' = space1, ' ' = space2)

sel1 <- df$activity == 'day 1'
sel2 <- df$activity == 'day 2'

idx1 <- which(df$activity %in% 'day 1')
idx2 <- which(df$activity %in% 'day 2')
n <- length(df$activity)

df1 <- df[(idx1 + 1):(idx2 - 1), ]
df2 <- df[(idx2 + 1):n, ]

df1[is.na(df1)] <- " "# replaces NAs with 2 blanks
df2[is.na(df2)] <- " " # replaces NAs with 2 blanks
```

### Session 1

To get the most out of the first session, do the pre-workshop homework before arriving. 

```{r}
kable(df1)
```

### Session 2

To get the most out of the second session, complete the sample report tutorial before the second session.  

```{r}
kable(df2)
```


--- 
Return to the [main page](../index.html) 

