---
title: "learning objectives"
output:
  html_document:
    keep_md: yes
---

[\\]: this is an Rmd comment

### description 

In an interactive environment, we discuss reproducible research---what it is and why we care---followed by a hands-on guided tour of creating a reproducible analysis and report. The software tutorials are self-paced; participants moving ahead more quickly should have time apply the principles to work of their own. 

We treat the following aspects of creating a technical document: 

- Reading, manipulating, and analyzing data 
- Creating tables and graphs 
- Writing equations and in-line results 
- Managing headings, references, and external media 

###  objectives 

By the end of the workshop participants should be able to: 

- Describe the problems that reproducibility helps solve 
- Identify non-reproducible practices in their current workflow 
- List two basic principles of reproducible research 
- Organize directories and files for reproducibility 
- Create a reproducible report using R and RStudio

