---
layout: page
title: workshop
tagline: reproducible research for the R novice
description: Introduces R, RStudio, and R Markdown as tools to create
             a dynamically reproducible report. For R novices. 
output: 
  html_document:
    keep_md: TRUE
---

[\\]: this is an Rmd comment

Welcome! The goal of the workshop is to introduce the R novice to reproducible research in the context of creating a reproducible report using R, RStudio, and knitr.  


### getting started

The pre-workshop homework should take about 30 minutes. 

- [pre-workshop homework](pages/102_pre-workshop-hw.html) 
- [learning objectives](pages/101_learning-objectives.html)

The day of the workshop:  

- [workshop agenda](pages/103_workshop-agenda.html) 
- surveying the reproducible research ecosystem 
- considering a sample report 

### tutorials 

We'll start the tutorials together but I'll let you work at your own pace as soon as possible. 

- [getting organized](pages/104_getting-organized.html)
- [initializing an Rmd script](pages/195_initializing-an-Rmd-script.html)
- [examine the wide-form data](pages/108_examine-wide-data.html)
- [data reshaping](pages/109_data-reshaping.html)
- [data tidying](pages/110_data-tidying.html)
- [linear regression](pages/111_linear-regression.html) 
- calibration graph 
- client report 



### next steps 

- what to do when the data change 
- planning for reproducibility 
- starting your own project 
- looking ahead 



### acknowledgments 

Many thanks to many folks in the R community for posting their work in their blogs and repos. I would especially like to thank: 

- [Karl Broman](http://kbroman.org) for his  [tutorials](http://kbroman.org/pages/tutorials.html) that made the creation of these GitHub-hosted webpages *almost* painless 
- [Jenny Bryan](https://github.com/jennybc) for her [Stats545 material](http://stat545.com/) and for the
[Good enough practices](https://swcarpentry.github.io/good-enough-practices-in-scientific-computing/) paper for guidance on file naming and directory organization. 
- [Reproducible Science  Curriculum](https://github.com/Reproducible-Science-Curriculum) contributors for their reproducible research  teaching materials.
